name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DB_USER: "postgres"
          envkey_DB_PASSWORD: "postgres"
          envkey_DB_NAME: "crud_doctors_test"
          envkey_DB_HOST: "crud_doctors_db_test"
          envkey_DB_PORT: "5432"
          envkey_DB_CONNECTION: "postgresql"
          file_name: ".env.test"
      - name: Run E2E tests
        run: docker-compose -f docker-compose-tests.yml run crud_doctors_app npm run test:e2e