name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: "postgresql://postgres:postgres@crud_doctors_db_test:5432/crud_doctors_test"
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "crud_doctors_test"
          file_name: ".env.test"
      - name: Run E2E tests
        run: docker-compose -f docker-compose-tests.yml run crud_doctors_app npm run test:e2e
      - name: Run Doctor Controller Unit tests
        run: docker-compose -f docker-compose-tests.yml run crud_doctors_app npm run test
